import requests as req
import json
from datetime import datetime

BINANCE_P2P_URL = "https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search"

def fetch_p2p(fiat, trade_type):
    payload = {
        "asset": "USDT",
        "fiat": fiat,
        "merchantCheck": False,
        "page": 1,
        "payTypes": [],
        "publisherType": "merchant",
        "rows": 1,
        "tradeType": trade_type,
        "transAmount": None,
        "classifies": ["mass", "profession", "tier1", "tier2"]
    }
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
    }
    try:
        response = req.post(BINANCE_P2P_URL, json=payload, headers=headers, timeout=10)
        data = response.json()
        if data.get("data") and len(data["data"]) > 0:
            return float(data["data"][0]["adv"]["price"])
        return 0
    except:
        return 0

def generate_report():
    # Parámetros del test
    monto_envio = 1000 # 1000 CLP de ejemplo
    comision_pct = 3.0 # Tu ganancia del 3%
    
    # Obtener datos reales de Binance
    tasa_clp = fetch_p2p("CLP", "BUY")
    tasa_ves = fetch_p2p("VES", "SELL")
    
    if tasa_clp == 0 or tasa_ves == 0:
        print("Error al obtener tasas de Binance.")
        return

    # Cálculos
    tasa_mercado = tasa_ves / tasa_clp
    tasa_cliente = tasa_mercado * (1 - (comision_pct / 100))
    monto_ves = monto_envio * tasa_cliente
    ganancia_clp = monto_envio * (comision_pct / 100)
    
    ahora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    reporte = f"""================================================================================
          REPORTE DE TEST: CHILE (CLP) A VENEZUELA (VES)
================================================================================
Fecha del Test: {ahora}
Monto de Prueba: {monto_envio} CLP
Margen de Ganancia: {comision_pct}%
--------------------------------------------------------------------------------

PASO 1: CONSULTA DE MERCADO EN CHILE (ORIGEN)
Binance nos dice que para comprar 1 USDT en Chile, el mejor precio es:
=> 1 USDT = {tasa_clp:,.2f} CLP

PASO 2: CONSULTA DE MERCADO EN VENEZUELA (DESTINO)
Binance nos dice que si vendemos 1 USDT en Venezuela, nos dan:
=> 1 USDT = {tasa_ves:,.2f} VES

PASO 3: CÁLCULO DE LA TASA DE MERCADO (CROSS RATE)
Dividimos la tasa de destino entre la tasa de origen para saber cuánto vale 
1 CLP en Bolívares (VES) de forma "pura" (sin ganancia):
Cálculo: {tasa_ves} / {tasa_clp}
=> Tasa Mercado: {tasa_mercado:.8f} VES/CLP

PASO 4: CÁLCULO DE LA TASA FINAL (TU NEGOCIO)
Restamos tu comisión ({comision_pct}%) a la tasa de mercado para que tú
obtengas tu beneficio.
Cálculo: {tasa_mercado:.8f} * (1 - {comision_pct/100})
=> Tasa al Cliente: {tasa_cliente:.8f} VES/CLP

--------------------------------------------------------------------------------
RESULTADO PARA EL CLIENTE:
--------------------------------------------------------------------------------
Si el cliente te entrega 1,000 CLP:
Multiplicamos: {monto_envio} * {tasa_cliente:.8f}
=> EL CLIENTE RECIBE: {monto_ves:,.2f} VES

--------------------------------------------------------------------------------
RESUMEN DE GANANCIA PARA TI:
--------------------------------------------------------------------------------
Tú recibes 1,000 CLP. Tu ganancia es el {comision_pct}% de ese monto.
Cálculo: {monto_envio} * {comision_pct/100}
=> TU GANANCIA: {ganancia_clp:,.2f} CLP

================================================================================
Este cálculo utiliza el puente de USDT en Binance P2P.
Generated by TazaCalculadora System Test.
================================================================================
"""

    with open("REPORTE_TEST_CLP_VES.txt", "w") as f:
        f.write(reporte)
    
    print("Reporte generado con éxito: REPORTE_TEST_CLP_VES.txt")
    print(reporte)

if __name__ == "__main__":
    generate_report()
